#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Class-Singleton
Version  : 1.6
Release  : 35
URL      : https://cpan.metacpan.org/authors/id/S/SH/SHAY/Class-Singleton-1.6.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/S/SH/SHAY/Class-Singleton-1.6.tar.gz
Summary  : 'Implementation of a "Singleton" class '
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Class-Singleton-license = %{version}-%{release}
Requires: perl-Class-Singleton-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Test::More)

%description
NAME
Class::Singleton - Implementation of a "Singleton" class
SYNOPSIS
use Class::Singleton;

%package dev
Summary: dev components for the perl-Class-Singleton package.
Group: Development
Provides: perl-Class-Singleton-devel = %{version}-%{release}
Requires: perl-Class-Singleton = %{version}-%{release}

%description dev
dev components for the perl-Class-Singleton package.


%package license
Summary: license components for the perl-Class-Singleton package.
Group: Default

%description license
license components for the perl-Class-Singleton package.


%package perl
Summary: perl components for the perl-Class-Singleton package.
Group: Default
Requires: perl-Class-Singleton = %{version}-%{release}

%description perl
perl components for the perl-Class-Singleton package.


%prep
%setup -q -n Class-Singleton-1.6
cd %{_builddir}/Class-Singleton-1.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Class-Singleton
cp %{_builddir}/Class-Singleton-1.6/Copying %{buildroot}/usr/share/package-licenses/perl-Class-Singleton/18eaf66587c5eea277721d5e569a6e3cd869f855
cp %{_builddir}/Class-Singleton-1.6/LICENCE %{buildroot}/usr/share/package-licenses/perl-Class-Singleton/2a7c640d77e195b3674ec8e5e126b3ac7a1ce1a1
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Class::Singleton.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Class-Singleton/18eaf66587c5eea277721d5e569a6e3cd869f855
/usr/share/package-licenses/perl-Class-Singleton/2a7c640d77e195b3674ec8e5e126b3ac7a1ce1a1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.34.0/Class/Singleton.pm
